name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  HEADLESS: true

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Build the example project
        run: dotnet build
      
      - name: Run the example tests
        run: dotnet test --no-build --verbosity normal